# Generated by Django 4.2.7 on 2024-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_temporarypost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='temporarypost',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
