# Generated by Django 4.2.7 on 2024-05-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_remove_temporaryalbum_album_and_more'),
        ('posts', '0004_alter_post_text_alter_temporarypost_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryPost',
        ),
    ]
