# Generated by Django 4.2.7 on 2024-04-16 17:16

from django.db import migrations, models
import dynamic_filenames
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No name album', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid_id', models.UUIDField(default=uuid.uuid4)),
                ('uuid_url', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('user', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='post_images/{instance.user.id}/{name}{ext}'))),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_picture', models.BooleanField(default=False)),
                ('is_preview', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('user', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TemporaryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='temp_post_images/{uuid:x}{ext}'))),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('user', '-created_at'),
            },
        ),
    ]
