# Generated by Django 4.2.7 on 2024-04-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('user', '-created_at')},
        ),
    ]
