# Generated by Django 4.2.7 on 2024-04-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_imageeditdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageeditdescription',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imageeditdescription',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_image_description', to='gallery.image'),
        ),
    ]
