# Generated by Django 4.2.7 on 2024-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_remove_album_preview_image_album_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
