# Generated by Django 4.2.7 on 2024-05-05 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_album_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='uuid_id',
        ),
        migrations.AddField(
            model_name='temporaryalbum',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='temporaryalbum',
            name='uuid_url',
            field=models.CharField(default=111, max_length=32),
            preserve_default=False,
        ),
    ]
