# Generated by Django 4.2.7 on 2024-05-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('gallery', '0010_remove_album_uuid_id_temporaryalbum_uuid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='temporaryalbum',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_albums', to='posts.temporarypost'),
        ),
    ]
