# Generated by Django 4.2.7 on 2024-05-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_temporarypost_post'),
        ('gallery', '0011_alter_album_post_alter_temporaryalbum_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageeditdescription',
            name='post',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='edit_image_description', to='posts.temporarypost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryalbum',
            name='album',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='temp_albums', to='gallery.album'),
            preserve_default=False,
        ),
    ]
