# Generated by Django 4.2.7 on 2024-05-06 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_temporarypost_post'),
        ('gallery', '0012_imageeditdescription_post_temporaryalbum_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryalbum',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_albums', to='gallery.album'),
        ),
        migrations.AlterField(
            model_name='temporaryimage',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temp_images', to='posts.temporarypost'),
            preserve_default=False,
        ),
    ]
