# Generated by Django 4.2.7 on 2024-05-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_text_alter_temporarypost_text'),
        ('gallery', '0013_alter_temporaryalbum_album_alter_temporaryimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_images', to='posts.temporarypost'),
        ),
    ]
