# Generated by Django 4.2.7 on 2024-05-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_rename_is_preview_image_edit_to_delete_album_uuid_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryalbum',
            name='album',
        ),
        migrations.RemoveField(
            model_name='temporaryalbum',
            name='post',
        ),
        migrations.RemoveField(
            model_name='temporaryalbum',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImageEditDescription',
        ),
        migrations.DeleteModel(
            name='TemporaryAlbum',
        ),
    ]
