# Generated by Django 4.2.7 on 2024-09-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
