# Generated by Django 4.2.7 on 2024-09-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_user_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
