# Generated by Django 4.2.7 on 2024-09-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_lastvisitedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
